import { useEffect, useMemo, useRef, useState, type FormEvent } from 'react';
import './ProductManagementPage.css';
import type { ProductOptionGroupDraft } from './ProductOptionsEditor.tsx';

type Language = 'en' | 'ar';
type Vertical = { vertical_key: string; label_en: string; label_ar: string; capabilities: Record<string, unknown>; active: boolean };
type PriceRule = { id: string; quantity_min: number; quantity_max: number | null; material: string | null; finishing: string | null; unit_price: number | string; design_fee?: number | string; active_from: string; active_to: string | null };
type Variant = { id: string; sku: string; name: string; width_cm?: number | null; height_cm?: number | null; material?: string | null; finishing?: string | null; available_quantity?: number | null; attributes?: Record<string, unknown>; active?: boolean; price_rules?: PriceRule[] };
type ProductOptionGroup = ProductOptionGroupDraft & { id?: string };
type ProductImageGeneration = { id: string; image_path: string; model?: string | null; selected: boolean; created_at: string };
type Product = { id: string; sku: string; name: string; category: string; description?: string | null; material_description?: string; image_path?: string; base_unit?: string; vertical_key?: string; attributes?: Record<string, unknown>; active?: boolean; demo_only?: boolean; requires_design?: boolean; requires_size?: boolean; allow_customer_design_upload?: boolean; product_option_groups?: ProductOptionGroup[]; product_variants?: Variant[] };
type Props = { lang: Language; products: Product[]; verticals: Vertical[]; busy: boolean; imageAllowance: { included: number; used: number; remaining: number }; imageGenerations: Record<string, ProductImageGeneration[]>; onLoadImages: (productId: string) => void; onGenerateImage: (productId: string) => void; onSelectGeneratedImage: (productId: string, generationId: string) => void; onCreateProduct: (event: FormEvent<HTMLFormElement>) => Promise<void>; onDeleteProduct: (product: Product) => Promise<boolean>; onToggleProduct: (product: Product) => void; onEndPriceRule: (id: string, activeTo: string, reason: string) => void; onUpdateShopPrice: (variantId: string, unitPrice: string, designFee: string, reason: string) => Promise<boolean>; onUpdateProduct: (id: string, fields: { name: string; category: string; base_unit: string; description: string; material_description?: string; allow_customer_design_upload?: boolean; image_path?: string; vertical_key: string; attributes: string }) => Promise<boolean>; onUploadProductImage: (productId: string, file: File) => Promise<boolean>; onRemoveProductImage: (productId: string, path: string) => Promise<boolean>; onUpdateVariantCapacity: (id: string, quantity: number | null) => Promise<boolean>; onConfigureProductOffer: (productId: string, unitPrice: string, availableQuantity: string) => Promise<boolean> };

const today = new Date().toISOString().slice(0, 10);

export function ProductManagementPage({ lang, products, verticals, busy, imageAllowance, imageGenerations, onLoadImages, onGenerateImage, onSelectGeneratedImage, onCreateProduct, onDeleteProduct, onToggleProduct, onEndPriceRule, onUpdateShopPrice, onUpdateProduct, onUploadProductImage, onRemoveProductImage, onUpdateVariantCapacity, onConfigureProductOffer }: Props) {
  const [retirements, setRetirements] = useState<Record<string, { date: string; reason: string }>>({});
  const [capacityInputs, setCapacityInputs] = useState<Record<string, string>>({});
  const [offerInputs, setOfferInputs] = useState<Record<string, { price: string; quantity: string }>>({});
  const [editing, setEditing] = useState<{ id: string; name: string; category: string; base_unit: string; description: string; material_description: string; allow_customer_design_upload: boolean; vertical_key: string; attributes: string } | null>(null);
  const [search, setSearch] = useState('');
  const [page, setPage] = useState(1);
  const [allowanceReason, setAllowanceReason] = useState('');
  const [createImagePreview, setCreateImagePreview] = useState('');
  const [pendingImages, setPendingImages] = useState<Record<string, { file: File; preview: string }>>({});
  const previewUrls = useRef(new Set<string>());
  const ar = lang === 'ar';
  useEffect(() => () => previewUrls.current.forEach((url) => URL.revokeObjectURL(url)), []);
  const operationalProducts = products.filter((product) => !product.demo_only && product.active !== false);
  const visibleProducts = useMemo(() => products.filter((product) => !product.demo_only && `${product.name} ${product.sku} ${product.category}`.toLowerCase().includes(search.trim().toLowerCase())), [products, search]);
  const pageSize = 12;
  const pageCount = Math.max(1, Math.ceil(visibleProducts.length / pageSize));
  const pageProducts = visibleProducts.slice((page - 1) * pageSize, page * pageSize);
  const variants = operationalProducts.flatMap((product) => (product.product_variants ?? []).map((variant) => ({ ...variant, productName: product.name })));
  return <section className="product-admin">
    <div className="product-admin-intro"><span className="eyebrow">{ar ? '01 / المنتجات' : '01 / PRODUCTS'}</span><p>{ar ? 'أضف المنتج وسعره والكمية مرة واحدة. اختر ظهوره للعملاء؛ ويمكنك إخفاؤه في أي وقت.' : 'Add a product with its price and stock in one step. Choose whether customers can see it, and hide it any time.'}</p></div>
    <div className="product-admin-forms">
      <section className="card product-admin-disclosure">
      <div className="panel-heading"><div><span className="eyebrow">01 / PRODUCT</span><h2>{ar ? 'إضافة منتج' : 'Add a product'}</h2><small>{ar ? 'الاسم والسعر والمخزون في نموذج واحد' : 'Name, price, and stock in one form'}</small></div></div>
      <form className="form-card product-admin-form" onSubmit={async (event) => { const form = event.currentTarget; await onCreateProduct(event); if (!(form.elements.namedItem('sku') as HTMLInputElement | null)?.value) { if (createImagePreview) URL.revokeObjectURL(createImagePreview); setCreateImagePreview(''); } }}>
        <span className="eyebrow">01 / PRODUCT</span><h2>{ar ? 'منتج جديد' : 'Add a product'}</h2>
        <div className="form-row"><label>SKU<input name="sku" required maxLength={80} /></label><label>{ar ? 'الاسم' : 'Name'}<input name="name" required maxLength={200} /></label></div>
        <div className="form-row"><label>{ar ? 'الفئة' : 'Category'}<input name="category" required maxLength={80} placeholder="stickers, flyers, cards" /></label><label>{ar ? 'وحدة البيع' : 'Base unit'}<input name="base_unit" required maxLength={40} placeholder="piece, set, roll" /></label></div>
        <div className="form-row"><label>{ar ? 'مجال المتجر' : 'Store vertical'}<select name="vertical_key" defaultValue="printing" required>{verticals.map((vertical) => <option key={vertical.vertical_key} value={vertical.vertical_key}>{ar ? vertical.label_ar : vertical.label_en}</option>)}</select></label><label>{ar ? 'سعر الوحدة (جنيه)' : 'Selling price per unit (EGP)'}<input name="unit_price" type="number" min="0" step="0.01" required /></label></div>
        <div className="form-row"><label>{ar ? 'الكمية المتاحة' : 'Quantity available'}<input name="available_quantity" type="number" min="0" step="1" placeholder={ar ? 'اتركها فارغة للطلب حسب التصنيع' : 'Leave blank for made-to-order'} /></label><label>{ar ? 'رسوم خدمة التصميم (اختياري · جنيه)' : 'Design service fee (optional · EGP)'}<input name="design_fee" type="number" min="0" step="0.01" placeholder={ar ? 'اتركها فارغة إذا لم تكن الخدمة متاحة' : 'Leave blank if design service is not offered'} /><small className="subtext">{ar ? 'أدخل رسماً فقط للمنتجات التي تقدم لها خدمة تصميم.' : 'Enter a fee only for products that offer shop design.'}</small></label></div>
        <div className="form-row"><label>{ar ? 'الوصف (اختياري)' : 'Description (optional)'}<textarea name="description" rows={2} maxLength={4000} /></label><label>{ar ? 'صورة المنتج (اختياري)' : 'Product photo (optional)'}<input name="image" type="file" accept="image/jpeg,image/png,image/webp" onChange={(event) => { if (createImagePreview) { URL.revokeObjectURL(createImagePreview); previewUrls.current.delete(createImagePreview); } const file = event.currentTarget.files?.[0]; const url = file ? URL.createObjectURL(file) : ''; if (url) previewUrls.current.add(url); setCreateImagePreview(url); }} /><small className="subtext">JPG, PNG, WebP · 8 MB max</small></label></div>{createImagePreview && <img className="product-image-preview" src={createImagePreview} alt={ar ? 'معاينة صورة المنتج قبل الإنشاء' : 'Product image preview before creation'} />}
        <details className="product-printing-details"><summary>{ar ? 'تفاصيل طباعة اختيارية' : 'Optional printing details'}</summary><div className="form-row"><label>{ar ? 'الخامة' : 'Material'}<input name="material" maxLength={120} placeholder="Waterproof vinyl, 300 gsm…" /></label><label>{ar ? 'العرض (سم)' : 'Width (cm)'}<input name="width_cm" type="number" min="0.01" step="0.01" /></label><label>{ar ? 'الارتفاع (سم)' : 'Height (cm)'}<input name="height_cm" type="number" min="0.01" step="0.01" /></label></div></details>
        <label className="product-store-visibility"><input name="show_in_store" type="checkbox" defaultChecked />{ar ? 'إظهار هذا المنتج في متجر العملاء بعد الحفظ' : 'Show this product in the customer store after saving'}</label>
        <button className="primary" disabled={busy}>{ar ? 'إضافة المنتج' : 'Create product'}</button>
      </form>
      </section>
    </div>
    <section className="card product-admin-list"><div className="panel-heading"><div><span className="eyebrow">{visibleProducts.length.toString().padStart(2, '0')} {ar ? 'منتجات' : 'PRODUCTS'}</span><h2>{ar ? 'المنتجات' : 'Products'}</h2></div><div className="product-admin-list-tools"><input className="search product-admin-search" aria-label={ar ? 'بحث المنتجات' : 'Search products'} placeholder={ar ? 'ابحث بالاسم أو الفئة أو SKU' : 'Search name, category, or SKU'} value={search} onChange={(event) => { setSearch(event.target.value); setPage(1); }} /></div></div>
      {visibleProducts.length === 0 ? <div className="dashboard-empty"><p>{ar ? 'لا توجد منتجات بعد. أضف أول منتج لبدء الكتالوج.' : 'No products yet. Add your first product to start the catalog.'}</p></div> : <div className="product-admin-table compact-catalog"><div className="product-admin-table-head"><span>PRODUCT / DETAILS</span><span>STATE</span><span>AVAILABILITY</span><span>EDIT</span></div>{pageProducts.map((product) => {
        const isEditing = editing?.id === product.id;
        const variantRows = product.product_variants ?? [];
        const activePrices = variantRows.flatMap((variant) => (variant.price_rules ?? []).filter((rule) => rule.active_from <= today && (!rule.active_to || rule.active_to >= today)).map((rule) => Number(rule.unit_price))).filter((value) => Number.isFinite(value) && value >= 0);
        const startingPrice = activePrices.length ? Math.min(...activePrices) : null;
        return <article className="product-admin-row" key={product.id}>
          {isEditing ? <form className="product-admin-edit" onSubmit={async (event) => {
            event.preventDefault();
            const form = new FormData(event.currentTarget);
            const saved = await onUpdateProduct(product.id, { name: String(form.get('name') ?? ''), category: String(form.get('category') ?? ''), base_unit: String(form.get('base_unit') ?? ''), description: String(form.get('description') ?? ''), material_description: String(form.get('material_description') ?? ''), allow_customer_design_upload: form.has('allow_customer_design_upload'), vertical_key: String(form.get('vertical_key') ?? 'printing'), attributes: String(form.get('attributes') ?? '{}') });
            if (saved) setEditing(null);
          }}>
            <label>{ar ? 'الاسم' : 'Name'}<input name="name" defaultValue={product.name} required maxLength={200} /></label>
            <label>{ar ? 'الفئة' : 'Category'}<input name="category" defaultValue={product.category} required maxLength={80} /></label>
            <label>{ar ? 'وحدة البيع' : 'Base unit'}<input name="base_unit" defaultValue={product.base_unit ?? ''} required maxLength={40} /></label>
            <label>{ar ? 'الخامة' : 'Material'}<input name="material_description" defaultValue={product.material_description ?? ''} maxLength={240} /></label>
            <label className="check-row"><input name="allow_customer_design_upload" type="checkbox" defaultChecked={product.allow_customer_design_upload === true} />{ar ? 'السماح برفع تصميم العميل لهذا المنتج' : 'Allow customer design upload for this product'}</label>
            <input type="hidden" name="vertical_key" value={product.vertical_key ?? 'printing'} />
            <input type="hidden" name="attributes" value={JSON.stringify(product.attributes ?? {})} />
            <label>{ar ? 'الوصف' : 'Description'}<textarea name="description" defaultValue={product.description ?? ''} maxLength={4000} /></label>
            <div className="product-admin-edit-actions"><button className="primary compact" disabled={busy}>{ar ? 'حفظ' : 'Save'}</button><button type="button" className="secondary compact" onClick={() => setEditing(null)}>{ar ? 'إلغاء' : 'Cancel'}</button></div>
          </form> : <div className="product-admin-identity"><span className="product-admin-thumb">{product.image_path ? <img src={`${String(import.meta.env.VITE_SUPABASE_URL ?? '').replace(/\/$/, '')}/storage/v1/object/public/storefront-assets/${product.image_path.split('/').map(encodeURIComponent).join('/')}`} alt="" /> : <span>▧</span>}</span><strong>{product.name}</strong><small>{product.sku} · {product.category} · {variantRows.length === 0 ? (ar ? 'يحتاج سعر وكمية' : 'Price & quantity needed') : `${variantRows.length} ${ar ? 'أنواع' : 'formats'}`}</small><small>{product.material_description || (ar ? 'بدون خامة وصفية' : 'No descriptive material')}</small><small className="product-row-price">{startingPrice === null ? (ar ? 'أضف سعر البيع أدناه' : 'Add selling price below') : `${ar ? 'يبدأ من' : 'From'} ${new Intl.NumberFormat(ar ? 'ar-EG' : 'en-EG', { style: 'currency', currency: 'EGP', maximumFractionDigits: 2 }).format(startingPrice)} / ${ar ? 'وحدة' : 'unit'}`}</small><label className="compact-image-upload">{ar ? 'تغيير الصورة' : 'Change image'}<input type="file" accept="image/jpeg,image/png,image/webp" disabled={busy} onChange={(event) => { const file = event.currentTarget.files?.[0]; if (file) { const previous = pendingImages[product.id]?.preview; if (previous) { URL.revokeObjectURL(previous); previewUrls.current.delete(previous); } const preview = URL.createObjectURL(file); previewUrls.current.add(preview); setPendingImages((current) => ({ ...current, [product.id]: { file, preview } })); } event.currentTarget.value = ''; }} /></label>{product.image_path && <button type="button" className="text-button" disabled={busy} onClick={() => void onRemoveProductImage(product.id, String(product.image_path))}>{ar ? 'إزالة' : 'Remove image'}</button>}</div>}
          {pendingImages[product.id] && <div className="product-image-pending"><img className="product-image-preview" src={pendingImages[product.id].preview} alt={ar ? 'معاينة صورة بديلة' : 'Replacement image preview'} /><div><button type="button" className="primary compact" disabled={busy} onClick={async () => { const pending = pendingImages[product.id]; if (pending && await onUploadProductImage(product.id, pending.file)) { URL.revokeObjectURL(pending.preview); previewUrls.current.delete(pending.preview); setPendingImages((current) => { const next = { ...current }; delete next[product.id]; return next; }); } }}>{ar ? 'حفظ الصورة' : 'Save image'}</button><button type="button" className="secondary compact" onClick={() => { const pending = pendingImages[product.id]; if (pending) { URL.revokeObjectURL(pending.preview); previewUrls.current.delete(pending.preview); } setPendingImages((current) => { const next = { ...current }; delete next[product.id]; return next; }); }}>{ar ? 'إلغاء' : 'Cancel'}</button></div></div>}<span className={`status-pill ${product.demo_only ? 'status-rejected' : product.active === false ? 'status-rejected' : 'status-approved'}`}>{product.demo_only ? (ar ? 'عينة فقط' : 'Demo only') : product.active === false ? (ar ? 'مخفي' : 'Hidden') : (ar ? 'نشط' : 'Active')}</span>
          <div className="catalog-row-availability"><span>{variantRows.reduce((sum, variant) => sum + (variant.available_quantity == null ? 0 : Number(variant.available_quantity)), 0) || (variantRows.some((variant) => variant.available_quantity == null) ? (ar ? 'بلا حد' : 'Unlimited') : 0)}</span><small>{ar ? 'متاح' : 'available'}</small></div>
          <details className="product-image-ai" onToggle={(event) => { if (event.currentTarget.open) onLoadImages(product.id); }}><summary>{ar ? 'صور إضافية بالذكاء الاصطناعي' : 'Additional AI images'} · {imageAllowance.remaining}/{imageAllowance.included} {ar ? 'متبقية' : 'included remaining'}</summary><p className="subtext">{ar ? 'صور اختيارية للمراجعة. لا تغيّر الصورة الأساسية إلا بعد اختيارك. الحد المجاني مشترك بين منتجات المتجر.' : 'Optional candidate images for review. The primary image changes only after you select one. The included free allowance is shared by this shop.'}</p><button type="button" className="secondary compact" disabled={busy || imageAllowance.remaining < 1} onClick={() => onGenerateImage(product.id)}>{imageAllowance.remaining < 1 ? (ar ? 'اكتمل الحد المجاني · الدفع الإضافي غير مهيأ' : 'Free limit reached · paid extras are not configured') : (ar ? 'إنشاء صورة إضافية' : 'Generate an additional image')}</button><div className="product-generated-images">{(imageGenerations[product.id] ?? []).map((image) => <article key={image.id}><img src={`${String(import.meta.env.VITE_SUPABASE_URL ?? '').replace(/\/$/, '')}/storage/v1/object/public/storefront-assets/${image.image_path.split('/').map(encodeURIComponent).join('/')}`} alt={ar ? 'صورة منتج مولدة للمراجعة' : 'Generated product image for review'} /><small>{image.model ?? 'AI-generated'}</small><button type="button" className={image.selected ? 'primary compact' : 'secondary compact'} disabled={busy || image.selected} onClick={() => onSelectGeneratedImage(product.id, image.id)}>{image.selected ? (ar ? 'الصورة الأساسية' : 'Primary image') : (ar ? 'اجعلها الصورة الأساسية' : 'Set as primary')}</button></article>)}</div></details>
          <button type="button" className="secondary compact" disabled={busy} onClick={() => onToggleProduct(product)}>{product.active === false ? (ar ? 'إظهار في المتجر' : 'Show in store') : (ar ? 'إخفاء من المتجر' : 'Hide from store')}</button>
          {!isEditing && <button type="button" className="secondary compact" disabled={busy} onClick={() => setEditing({ id: product.id, name: product.name, category: product.category, base_unit: product.base_unit ?? '', description: product.description ?? '', material_description: product.material_description ?? '', allow_customer_design_upload: product.allow_customer_design_upload === true, vertical_key: product.vertical_key ?? 'printing', attributes: JSON.stringify(product.attributes ?? {}, null, 2) })}>{ar ? 'تعديل' : 'Edit'}</button>}
          <button type="button" className="danger compact" disabled={busy} onClick={() => { if (window.confirm(ar ? 'حذف المنتج نهائياً؟ لا يمكن التراجع عن ذلك.' : 'Permanently delete this product? This cannot be undone.')) void onDeleteProduct(product); }}>{ar ? 'حذف نهائياً' : 'Delete permanently'}</button>
          {variantRows.length === 0 && <form className="product-offer-editor" onSubmit={async (event) => { event.preventDefault(); const values = offerInputs[product.id] ?? { price: '', quantity: '' }; if (await onConfigureProductOffer(product.id, values.price, values.quantity)) setOfferInputs((all) => ({ ...all, [product.id]: values })); }}>
            <strong>{ar ? 'أكمل إعداد المنتج' : 'Finish product setup'}</strong>
            <label>{ar ? 'سعر الوحدة (جنيه)' : 'Unit price (EGP)'}<input required type="number" min="0" step="0.01" value={offerInputs[product.id]?.price ?? ''} onChange={(event) => setOfferInputs((all) => ({ ...all, [product.id]: { price: event.target.value, quantity: all[product.id]?.quantity ?? '' } }))} /></label>
            <label>{ar ? 'الكمية المتاحة' : 'Available quantity'}<input type="number" min="0" step="1" placeholder={ar ? 'اتركها فارغة للطلب حسب التصنيع' : 'Blank = made to order'} value={offerInputs[product.id]?.quantity ?? ''} onChange={(event) => setOfferInputs((all) => ({ ...all, [product.id]: { price: all[product.id]?.price ?? '', quantity: event.target.value } }))} /></label>
            <button className="primary compact" disabled={busy}>{ar ? 'حفظ السعر والكمية' : 'Save price & quantity'}</button>
          </form>}
          <details open className="product-variants-details"><summary>{ar ? 'السعر والمخزون' : 'Price and stock'}</summary>{variantRows.map((variant) => <details open className="product-admin-rule-list variant-admin-details" key={variant.id}>
            <summary><strong>{variant.name} · {variant.sku}</strong><small>{product.vertical_key === 'printing' ? (variant.material || (ar ? 'لم تُحدد خامة' : 'Material not set')) : (ar ? 'مواصفات المنتج' : 'Product specifications')} · {variant.available_quantity == null ? (ar ? 'متاح بلا حد' : 'Unlimited availability') : `${variant.available_quantity} ${ar ? 'متاح للطلبات' : 'available to order'}`}</small></summary>
            <form className="capacity-editor" onSubmit={async (event) => {
              event.preventDefault();
              const value = capacityInputs[variant.id] ?? (variant.available_quantity == null ? '' : String(variant.available_quantity));
              const saved = await onUpdateVariantCapacity(variant.id, value.trim() === '' ? null : Number(value));
              if (saved) setCapacityInputs((all) => ({ ...all, [variant.id]: value }));
            }}>
              <label>{ar ? 'الكمية المتاحة' : 'Available quantity'}<input type="number" min="0" step="1" value={capacityInputs[variant.id] ?? (variant.available_quantity == null ? '' : String(variant.available_quantity))} placeholder={ar ? 'بلا حد' : 'Unlimited'} onChange={(event) => setCapacityInputs((all) => ({ ...all, [variant.id]: event.target.value }))} /></label>
              <small>{ar ? 'الكمية المتاحة حالياً للطلبات الجديدة؛ الصفر يوقف الطلبات.' : 'Remaining units for new orders; set 0 to pause ordering.'}</small>
              <button className="secondary compact" disabled={busy}>{ar ? 'حفظ المتاح' : 'Save availability'}</button>
            </form>
            {(() => {
              const currentRule = (variant.price_rules ?? []).find((rule) => rule.active_from <= today && (!rule.active_to || rule.active_to >= today));
              const latestRule = currentRule ?? [...(variant.price_rules ?? [])].sort((a, b) => b.active_from.localeCompare(a.active_from))[0];
              return <form className="capacity-editor product-price-editor" onSubmit={async (event) => {
                event.preventDefault();
                const form = new FormData(event.currentTarget);
                await onUpdateShopPrice(variant.id, String(form.get('unit_price') ?? ''), String(form.get('design_fee') ?? '0'), String(form.get('reason') ?? ''));
              }}>
                <label>{ar ? 'سعر الوحدة (جنيه)' : 'Unit price (EGP)'}<input name="unit_price" type="number" min="0" step="0.01" required defaultValue={latestRule?.unit_price ?? ''} /></label>
                <label>{ar ? 'رسوم التصميم' : 'Design fee'}<input name="design_fee" type="number" min="0" step="0.01" defaultValue={latestRule?.design_fee ?? 0} /></label>
                <label>{ar ? 'سبب التعديل' : 'Reason'}<input name="reason" required minLength={3} maxLength={500} defaultValue={ar ? 'تحديث السعر المعتمد' : 'Manager approved price update'} /></label>
                <small>{ar ? 'يسري السعر الجديد من الغد، مع حفظ سجل السعر السابق.' : 'New price takes effect tomorrow; the previous price stays in the audit history.'}</small>
                <button className="secondary compact" disabled={busy}>{ar ? 'حفظ السعر' : 'Save price'}</button>
              </form>;
            })()}
            {(variant.price_rules ?? []).length === 0 ? <small>{ar ? 'لا توجد قواعد تسعير داخلية.' : 'No shop price rules configured.'}</small> : variant.price_rules?.map((rule) => {
              const form = retirements[rule.id] ?? { date: rule.active_to ?? today, reason: '' };
              return <div className="product-admin-rule" key={rule.id}>
                <span>{Number(rule.quantity_min).toLocaleString()}–{rule.quantity_max === null ? '∞' : Number(rule.quantity_max).toLocaleString()} · {rule.material || 'Any material'} · EGP {Number(rule.unit_price).toFixed(2)} / unit · {rule.active_from} → {rule.active_to ?? (ar ? 'مفتوحة' : 'open')}</span>
                {rule.active_to === null && <div className="product-admin-rule-controls"><input type="date" aria-label={ar ? 'تاريخ انتهاء السعر' : 'Price rule end date'} min={rule.active_from} value={form.date} onChange={(event) => setRetirements((all) => ({ ...all, [rule.id]: { ...form, date: event.target.value } }))} /><input aria-label={ar ? 'سبب إنهاء قاعدة السعر' : 'Reason for ending this price rule'} required maxLength={500} placeholder={ar ? 'سبب التعديل' : 'Reason for ending this rule'} value={form.reason} onChange={(event) => setRetirements((all) => ({ ...all, [rule.id]: { ...form, reason: event.target.value } }))} /><button className="secondary compact" disabled={busy || form.reason.trim().length < 3} onClick={() => onEndPriceRule(rule.id, form.date, form.reason)}>{ar ? 'إنهاء السعر' : 'End price'}</button></div>}
              </div>;
            })}
          </details>)}</details>
        </article>;
      })}</div>}{visibleProducts.length > pageSize && <div className="catalog-pagination"><button className="secondary compact" disabled={page <= 1} onClick={() => setPage((value) => Math.max(1, value - 1))}>← {ar ? 'السابق' : 'Previous'}</button><span>{page} / {pageCount}</span><button className="secondary compact" disabled={page >= pageCount} onClick={() => setPage((value) => Math.min(pageCount, value + 1))}>{ar ? 'التالي' : 'Next'} →</button></div>}
    </section>
  </section>;
}
